### ISSUE TITLE
latest rofi versions dont show the proper kpl window initially

### ISSUE THREAD

**Issue by jasondaigo** [jp1995/kappa-launcher#16] opened 2022-08-29 12:14 UTC
it worked up to version 1.7.3 (stil works if i roll back). But 1.7.4 and 1.7.5 shows this initial window now. telling me rofi doesnt know what window to show. i can just hit escape and it still works after that. is there a workaround maybe. ?  for more convenience :-)
https://imgur.com/a/lBy3pqV

**Comment by jp1995** [comment] 2022-08-29 12:55
Interesting, I can't seem to reproduce this with rofi 1.7.5.

Every time rofi is called in the script it's in dmenu mode so I'm unsure why it would show that.

Is there anything interesting in the output when you run kpl in the terminal?

**Comment by jasondaigo** [comment] 2022-08-29 13:14
no only the standard stuff
```
Configuration file found, proceeding
json file successfully populated
```
i also created a new config, just in case. but thats not chaning anything

**Comment by jp1995** [comment] 2022-08-29 16:10
Took a bit of digging but I figured it out. The issue is in the fontname and fontsize function, which call `rofi -dump-xresources`, which has been deprecated.

Temporary workaround is to declare a font (and font size) in either kpl config or rofi config as this way the function never hits the deprecated call.

I'll fix it in a couple days and probably just remove that part of the functions.

**Comment by vtuhes** [comment] 2022-10-08 21:41
Just commented out the line in /usr/bin/kpl to avoid seeing the error Pepechill https://i.imgur.com/R6xfLfK.png.

**Comment by jp1995** [comment] 2023-07-09 12:47
Only took 9 months... should be fixed now :)

**Closed by jp1995** 2023-07-09 12:47 UTC
